package com.smallsinger.spw.tags;

import com.formdev.flatlaf.FlatDarkLaf;
import com.formdev.flatlaf.FlatLightLaf;
import com.formdev.flatlaf.FlatLaf;
import javax.swing.*;
import javax.swing.border.*;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.filechooser.FileSystemView;
import javax.swing.table.AbstractTableModel;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableColumnModel;
import javax.swing.table.TableRowSorter;
import java.awt.*;
import java.io.File;
import java.util.ArrayList;
import java.util.List;
import java.nio.file.Files;

final class TagWorkbenchWindow extends JFrame {
    private static final Color BG = new Color(246, 247, 249), CARD = Color.WHITE;
    private static final Color ACCENT = new Color(35, 109, 246), SUB = new Color(102, 110, 122);
    private final SongModel model = new SongModel();
    private final JTable table = new RoundedTable(model);
    private final TableRowSorter<SongModel> sorter = new TableRowSorter<>(model);
    private final JTextField listSearch = input();
    private final CoverView cover = new CoverView();
    private final JLabel coverInfo = new JLabel("", SwingConstants.CENTER);
    private final JTextField title = input(), artist = input(), album = input(), albumArtist = input();
    private final JTextField lyricist = input(), composer = input(), year = input(), track = input(), disc = input(), genre = input();
    private final JTextArea lyrics = textArea(8), comment = textArea(3);
    private final JLabel status = new JLabel("请选择音频文件开始");
    private final JLabel topHint = new JLabel("小提示：在三个区域点右键，就能分别匹配全部标签、基础标签或歌词啦~",SwingConstants.CENTER);
    private final Timer tipTimer;
    private JScrollPane metadataScroll;
    private final JComboBox<MusicSource> sourceBox = new JComboBox<>(MusicSources.ALL.toArray(MusicSource[]::new));
    private final JCheckBox followPlayback = new JCheckBox("跟随播放", true);
    private int current = -1;
    private static boolean dark = detectDarkMode();
    static { applyLook(); }

    TagWorkbenchWindow() {
        super("");
        getRootPane().putClientProperty("JRootPane.useWindowDecorations", true);
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new Dimension(1000, 680)); setSize(1000, 680); setLocationRelativeTo(null);
        JPanel root = new JPanel(new BorderLayout(14, 8)); root.setBorder(new EmptyBorder(0, 18, 12, 18));
        root.add(toolbar(), BorderLayout.NORTH); root.add(body(), BorderLayout.CENTER);
        status.setForeground(SUB); status.setHorizontalAlignment(SwingConstants.CENTER); status.setBorder(new EmptyBorder(0, 8, 0, 8));root.add(status, BorderLayout.SOUTH);
        setContentPane(root);
        String[] tips={"小提示：在三个区域点右键，就能分别匹配全部标签、基础标签或歌词啦~","你发现了吗？勾选“跟随播放”后，当前播放和切换到的歌曲都会自动进入列表~","列表有点挤？点一下右键，就能把它清得干干净净啦~"};int[] tipIndex={0};tipTimer=new Timer(4800,e->{tipIndex[0]=(tipIndex[0]+1)%tips.length;topHint.setText(tips[tipIndex[0]]);});tipTimer.start();
    }

    private JComponent toolbar() {
        JLabel heading=new JLabel("音乐标签工作台");heading.setFont(heading.getFont().deriveFont(Font.PLAIN,28f));heading.setVerticalAlignment(SwingConstants.BOTTOM);
        topHint.setForeground(UIManager.getColor("Label.disabledForeground"));topHint.setFont(topHint.getFont().deriveFont(11f));topHint.setVerticalAlignment(SwingConstants.BOTTOM);
        JPanel topLine=new JPanel(new BorderLayout(12,0));topLine.setOpaque(false);topLine.add(heading,BorderLayout.WEST);topLine.add(topHint,BorderLayout.CENTER);topLine.setPreferredSize(new Dimension(0,34));
        JPanel songActions=new JPanel(new GridLayout(1,3,5,0));songActions.setOpaque(false);songActions.add(button("添加音频",this::addFiles,false));songActions.add(button("全选",()->model.selectAll(true),false));songActions.add(button("取消全选",()->model.selectAll(false),false));
        JPanel sourceActions=new JPanel(new BorderLayout(5,0));sourceActions.setOpaque(false);sourceActions.add(new JLabel("标签源选择:"),BorderLayout.WEST);sourceBox.setRenderer(new CenterListRenderer());sourceBox.putClientProperty("JComponent.roundRect",true);sourceActions.add(sourceBox,BorderLayout.CENTER);
        FlowLayout actionFlow=new FlowLayout(FlowLayout.RIGHT,4,0);actionFlow.setAlignOnBaseline(true);JPanel tagActions=new JPanel(actionFlow);tagActions.setOpaque(false);tagActions.add(button("匹配选中",()->matchSelected(MatchScope.ALL,selectedSource()),true));tagActions.add(button("保存当前",this::saveCurrent,true));tagActions.add(button("保存选中",this::saveSelected,true));followPlayback.setOpaque(false);followPlayback.setHorizontalAlignment(SwingConstants.RIGHT);tagActions.add(followPlayback);
        JPanel controls=new JPanel(new RatioLayout(12));controls.setOpaque(false);controls.add(songActions);controls.add(sourceActions);controls.add(tagActions);controls.setPreferredSize(new Dimension(0,30));
        JPanel outer=new JPanel(new BorderLayout(0,3));outer.setOpaque(false);outer.add(topLine,BorderLayout.NORTH);outer.add(controls,BorderLayout.SOUTH);return outer;
    }

    private JComponent body() {
        table.setRowHeight(40); table.setShowGrid(false); table.setIntercellSpacing(new Dimension(0, 0));
        table.setRowSorter(sorter);
        table.setTableHeader(null);
        table.setDefaultRenderer(String.class,new CenterCellRenderer());
        table.setDefaultRenderer(Boolean.class,new CheckCellRenderer());
        table.addMouseListener(new java.awt.event.MouseAdapter(){public void mouseClicked(java.awt.event.MouseEvent e){int row=table.rowAtPoint(e.getPoint()),col=table.columnAtPoint(e.getPoint());if(row>=0&&col==0){int modelRow=table.convertRowIndexToModel(row);model.checked.set(modelRow,!model.checked.get(modelRow));model.fireTableCellUpdated(modelRow,0);}}});
        table.setSelectionMode(ListSelectionModel.SINGLE_SELECTION); table.getColumnModel().getColumn(0).setMinWidth(30);table.getColumnModel().getColumn(0).setPreferredWidth(30);table.getColumnModel().getColumn(0).setMaxWidth(30);
        table.getSelectionModel().addListSelectionListener(e -> { if (!e.getValueIsAdjusting()) showRow(table.getSelectedRow()); });
        JScrollPane tableScroll=scroll(table);tableScroll.setBorder(new EmptyBorder(0,0,0,0));JPanel list=new JPanel(new BorderLayout(0,5));list.setBorder(titled("歌曲列表"));list.add(songHeader(),BorderLayout.NORTH);list.add(tableScroll,BorderLayout.CENTER);JPanel searchBar=new JPanel(new BorderLayout(5,0));searchBar.setOpaque(false);listSearch.putClientProperty("JTextField.placeholderText","支持搜索除歌词外所有标签");listSearch.setHorizontalAlignment(SwingConstants.CENTER);JButton searchButton=button("搜索",this::applyListFilter,true);listSearch.addActionListener(e->applyListFilter());searchBar.add(listSearch,BorderLayout.CENTER);searchBar.add(searchButton,BorderLayout.EAST);list.add(searchBar,BorderLayout.SOUTH);
        installSourceMenu(list, MatchScope.ALL);
        cover.setPreferredSize(new Dimension(260, 260));
        JPanel metadata = new JPanel(new BorderLayout(0, 7)); metadata.setMinimumSize(new Dimension(330,400));metadata.setBorder(titled("标签信息")); JPanel coverWrap=new JPanel(new BorderLayout(0,0));coverWrap.setOpaque(false);JPanel coverCenter=new JPanel(new FlowLayout(FlowLayout.CENTER,0,0));coverCenter.setOpaque(false);coverCenter.add(cover);coverWrap.add(coverCenter,BorderLayout.CENTER);coverInfo.setForeground(UIManager.getColor("Label.disabledForeground"));coverInfo.setFont(coverInfo.getFont().deriveFont(10f));coverInfo.setPreferredSize(new Dimension(0,12));coverWrap.add(coverInfo,BorderLayout.SOUTH);metadata.add(coverWrap,BorderLayout.NORTH); JScrollPane fieldScroll=scroll(fields());metadataScroll=fieldScroll;comment.addMouseWheelListener(e->{JScrollBar bar=metadataScroll.getVerticalScrollBar();bar.setValue(bar.getValue()+e.getWheelRotation()*bar.getUnitIncrement(3));e.consume();});fieldScroll.setHorizontalScrollBarPolicy(ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);fieldScroll.getVerticalScrollBar().setUnitIncrement(36);metadata.add(fieldScroll, BorderLayout.CENTER); installSourceMenu(metadata, MatchScope.METADATA); installSourceMenu(fieldScroll, MatchScope.METADATA);
        JPanel lyricPanel = new JPanel(new BorderLayout(0, 8)); lyricPanel.setMinimumSize(new Dimension(340,400));lyricPanel.setBorder(titled("歌词")); JScrollPane lyricScroll=scroll(lyrics); lyricPanel.add(lyricScroll, BorderLayout.CENTER); installSourceMenu(lyricPanel, MatchScope.LYRICS); installSourceMenu(lyricScroll, MatchScope.LYRICS);
        list.setMinimumSize(new Dimension(0,0));metadata.setMinimumSize(new Dimension(0,0));lyricPanel.setMinimumSize(new Dimension(0,0));JPanel columns=new JPanel(new RatioLayout(12));columns.setOpaque(false);columns.add(list);columns.add(metadata);columns.add(lyricPanel);return columns;
    }

    private JPanel fields() {
        JPanel p = new ViewportWidthPanel(new GridBagLayout()); GridBagConstraints c = new GridBagConstraints();
        c.insets = new Insets(5, 5, 5, 5); c.fill = GridBagConstraints.HORIZONTAL; c.weightx = 1; int r = 0;
        r = row(p,c,r,"标题",title); r=row(p,c,r,"艺术家",artist); r=row(p,c,r,"专辑",album); r=row(p,c,r,"年份",year);
        JPanel nums=new JPanel(new GridBagLayout()); nums.setOpaque(false); GridBagConstraints nc=new GridBagConstraints();nc.gridy=0;nc.fill=GridBagConstraints.HORIZONTAL;nc.weightx=1;nc.gridx=0;nums.add(track,nc);nc.weightx=0;nc.gridx=1;nc.insets=new Insets(0,8,0,6);nums.add(new JLabel("碟号"),nc);nc.weightx=1;nc.gridx=2;nc.insets=new Insets(0,0,0,0);nums.add(disc,nc);
        c.gridwidth=1;c.gridx=0;c.gridy=r;c.weightx=0;p.add(new JLabel("音轨号"),c);c.gridx=1;c.weightx=1;p.add(nums,c);r++;
        r=row(p,c,r,"风格",genre); r=row(p,c,r,"专辑艺术家",albumArtist); r=row(p,c,r,"作曲家",composer); r=row(p,c,r,"作词家",lyricist); r=row(p,c,r,"注释",roundedTextArea(comment));c.gridx=0;c.gridy=r;c.gridwidth=2;c.weighty=1;c.fill=GridBagConstraints.VERTICAL;c.anchor=GridBagConstraints.NORTH;p.add(Box.createVerticalGlue(),c);
        return p;
    }

    @Override public void dispose(){if(tipTimer!=null)tipTimer.stop();super.dispose();}

    private void addFiles() {
        JFileChooser ch=new JFileChooser(FileSystemView.getFileSystemView()); ch.setMultiSelectionEnabled(true); ch.setFileFilter(new FileNameExtensionFilter("音频文件","mp3","flac","m4a","ogg","opus","wav","wma"));
        File currentFolder=CurrentMediaExtension.currentFolder(); if(currentFolder!=null&&currentFolder.isDirectory())ch.setCurrentDirectory(currentFolder);else{File[] roots=FileSystemView.getFileSystemView().getRoots();if(roots.length>0)ch.setCurrentDirectory(roots[0]);}
        if(ch.showOpenDialog(this)!=JFileChooser.APPROVE_OPTION)return; setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        for(File f:ch.getSelectedFiles())try{model.add(AudioTagService.read(f));}catch(Exception ex){status.setText("读取失败："+f.getName()+" · "+ex.getMessage());}
        setCursor(Cursor.getDefaultCursor()); if(model.getRowCount()>0&&table.getSelectedRow()<0)table.setRowSelectionInterval(0,0); status.setText("已载入 "+model.getRowCount()+" 首歌曲");
    }

    void openLibraryFolder(File folder){if(folder==null||!folder.isDirectory()||model.getRowCount()>0)return;status.setText("正在扫描音乐文件夹："+folder.getAbsolutePath());new Thread(()->{int[] count={0};try(var paths=Files.walk(folder.toPath())){paths.filter(Files::isRegularFile).filter(path->isAudio(path.getFileName().toString())).forEach(path->{try{AudioTagData data=AudioTagService.read(path.toFile());SwingUtilities.invokeLater(()->model.add(data));count[0]++;}catch(Exception ignored){}});SwingUtilities.invokeLater(()->{status.setText("音乐文件夹扫描完成："+count[0]+" 首");if(model.getRowCount()>0&&table.getSelectedRow()<0)table.setRowSelectionInterval(0,0);});}catch(Exception ex){SwingUtilities.invokeLater(()->status.setText("音乐文件夹扫描失败："+ex.getMessage()));}},"library-scan").start();}
    private static boolean isAudio(String name){String n=name.toLowerCase(java.util.Locale.ROOT);return n.endsWith(".mp3")||n.endsWith(".flac")||n.endsWith(".m4a")||n.endsWith(".ogg")||n.endsWith(".opus")||n.endsWith(".wav")||n.endsWith(".wma");}
    void openPlaybackFile(File file){if(!followPlayback.isSelected()||file==null||!file.isFile())return;sorter.setRowFilter(null);listSearch.setText("");for(int i=0;i<model.items.size();i++)if(model.items.get(i).file().equals(file)){selectModelRow(i);return;}try{model.add(AudioTagService.read(file));selectModelRow(model.getRowCount()-1);status.setText("已跟随当前播放："+file.getName());}catch(Exception ex){status.setText("无法载入当前播放歌曲："+ex.getMessage());}}

    private MusicSource selectedSource(){return (MusicSource)sourceBox.getSelectedItem();}
    private void matchSelected(MatchScope scope, MusicSource source) {
        sync(); List<Integer> rows=model.checkedRows(); if(rows.isEmpty()){status.setText("请先勾选需要匹配的歌曲");return;}
        status.setForeground(SUB);status.setText(source.name()+"匹配中…"); new Thread(()->{int ok=0,fail=0; for(int i:rows){AudioTagData d=model.items.get(i); try{
            String keyword=(d.title()+" "+d.artist()).trim(); if(keyword.isBlank())keyword=d.file().getName().replaceFirst("\\.[^.]+$","");
            MusicSource.Result m=source.search(keyword); if(m==null){fail++;continue;}
            boolean meta=scope!=MatchScope.LYRICS, lyric=scope!=MatchScope.METADATA;
            model.items.set(i,new AudioTagData(d.file(),meta?keep(m.title(),d.title()):d.title(),meta?keep(m.artist(),d.artist()):d.artist(),meta?keep(m.album(),d.album()):d.album(),meta?keep(m.albumArtist(),d.albumArtist()):d.albumArtist(),meta?keep(m.lyricist(),d.lyricist()):d.lyricist(),meta?keep(m.composer(),d.composer()):d.composer(),meta?keep(m.year(),d.year()):d.year(),meta?keep(m.track(),d.track()):d.track(),meta?keep(m.disc(),d.disc()):d.disc(),meta?keep(m.genre(),d.genre()):d.genre(),lyric?keep(m.lyrics(),d.lyrics()):d.lyrics(),meta?keep(m.comment(),d.comment()):d.comment(),meta&&m.cover()!=null?m.cover():d.cover()));ok++;
        }catch(Exception ex){fail++;}} int a=ok,b=fail; SwingUtilities.invokeLater(()->{model.fireTableDataChanged(); if(current>=0){int view=table.convertRowIndexToView(current);if(view>=0)showRow(view);} status.setForeground(b==0?new Color(45,170,90):new Color(225,70,70));status.setText("匹配完成：成功 "+a+"，失败 "+b+"（预览后再保存）");});},"tag-match").start();
    }
    private static String keep(String incoming,String old){return incoming==null||incoming.isBlank()?old:incoming;}
    private void installSourceMenu(JComponent target, MatchScope scope){JPopupMenu menu=new JPopupMenu();menu.putClientProperty("JComponent.roundRect",true);menu.putClientProperty("FlatLaf.style","arc: 14; borderCornerRadius: 14");JMenu sources=new JMenu(scope==MatchScope.ALL?"匹配全部标签":scope==MatchScope.METADATA?"匹配基础标签":"匹配歌词");sources.putClientProperty("FlatLaf.style","selectionArc: 12");for(MusicSource source:MusicSources.ALL){JMenuItem item=new JMenuItem(source.name());item.putClientProperty("JComponent.roundRect",true);item.putClientProperty("FlatLaf.style","selectionArc: 12");item.addActionListener(e->matchSelected(scope,source));sources.add(item);}menu.add(sources);if(scope==MatchScope.ALL){menu.addSeparator();JMenuItem clear=new JMenuItem("清空列表");clear.putClientProperty("FlatLaf.style","selectionArc: 12");clear.addActionListener(e->clearList());menu.add(clear);}applyPopup(target,menu);}
    private static void applyPopup(Component component,JPopupMenu menu){if(component instanceof JComponent jc){jc.setComponentPopupMenu(menu);jc.setInheritsPopupMenu(true);}if(component instanceof Container container)for(Component child:container.getComponents())applyPopup(child,menu);}
    private enum MatchScope { ALL, METADATA, LYRICS }

    private void showRow(int viewRow){if(viewRow<0)return;int r=table.convertRowIndexToModel(viewRow);if(r<0||r>=model.items.size())return;sync();current=r;AudioTagData d=model.items.get(r);title.setText(d.title());artist.setText(d.artist());album.setText(d.album());albumArtist.setText(d.albumArtist());lyricist.setText(d.lyricist());composer.setText(d.composer());year.setText(d.year());track.setText(d.track());disc.setText(d.disc());genre.setText(d.genre());lyrics.setText(d.lyrics());comment.setText(d.comment());cover.setCover(d.cover());if(d.cover()==null)coverInfo.setText("");else{ImageIcon original=new ImageIcon(d.cover());coverInfo.setText(original.getIconWidth()+" × "+original.getIconHeight()+"px    "+formatBytes(d.cover().length));}SwingUtilities.invokeLater(()->metadataScroll.getVerticalScrollBar().setValue(0));}
    private static String formatBytes(long bytes){if(bytes>=1024L*1024L)return String.format(java.util.Locale.ROOT,"%.1fMB",bytes/(1024d*1024d));return String.format(java.util.Locale.ROOT,"%.0fKB",Math.max(1,bytes/1024d));}
    private void applyListFilter(){String q=listSearch.getText().trim().toLowerCase(java.util.Locale.ROOT);if(q.isEmpty())sorter.setRowFilter(null);else sorter.setRowFilter(new RowFilter<>(){public boolean include(Entry<? extends SongModel,? extends Integer> entry){AudioTagData d=model.items.get(entry.getIdentifier());String tags=String.join("\n",d.title(),d.artist(),d.album(),d.albumArtist(),d.lyricist(),d.composer(),d.year(),d.track(),d.disc(),d.genre(),d.comment());return tags.toLowerCase(java.util.Locale.ROOT).contains(q);}});table.clearSelection();status.setText("筛选结果："+table.getRowCount()+" 首");}
    private void clearList(){sync();model.clear();sorter.setRowFilter(null);listSearch.setText("");table.clearSelection();current=-1;for(JTextField f:new JTextField[]{title,artist,album,albumArtist,lyricist,composer,year,track,disc,genre})f.setText("");lyrics.setText("");comment.setText("");cover.setCover(null);coverInfo.setText("");status.setText("列表已经清空啦~");}
    private void selectModelRow(int modelRow){int view=table.convertRowIndexToView(modelRow);if(view<0)return;table.setRowSelectionInterval(view,view);table.scrollRectToVisible(table.getCellRect(view,0,true));}
    private void sync(){if(current>=0&&current<model.items.size()){AudioTagData d=model.items.get(current);model.items.set(current,new AudioTagData(d.file(),title.getText(),artist.getText(),album.getText(),albumArtist.getText(),lyricist.getText(),composer.getText(),year.getText(),track.getText(),disc.getText(),genre.getText(),lyrics.getText(),comment.getText(),d.cover()));}}
    private void saveCurrent(){sync();if(current<0)return;try{AudioTagService.write(model.items.get(current));status.setText("保存成功："+model.items.get(current).file().getName());}catch(Exception ex){status.setText("保存失败："+ex.getMessage());}}
    private void saveSelected(){sync();int ok=0,fail=0;for(int i:model.checkedRows())try{AudioTagService.write(model.items.get(i));ok++;}catch(Exception ex){fail++;}status.setText("批量保存完成：成功 "+ok+"，失败 "+fail);}

    private static JButton button(String s,Runnable action,boolean primary){JButton b=new JButton(s);b.setFont(b.getFont().deriveFont(12f));b.setMargin(new Insets(5,9,5,9));b.setFocusPainted(false);b.putClientProperty("JButton.buttonType","roundRect");b.putClientProperty("JComponent.minimumWidth",60);b.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));if(primary){b.setBackground(ACCENT);b.setForeground(Color.WHITE);}b.addActionListener(e->action.run());return b;}
    private static JTextField input(){JTextField f=new JTextField();f.setMinimumSize(new Dimension(0,28));f.putClientProperty("JComponent.roundRect",true);f.putClientProperty("JTextField.placeholderText","");f.setMargin(new Insets(6,7,6,7));return f;}
    private static JTextArea textArea(int rows){JTextArea a=new JTextArea(rows,8);a.setMinimumSize(new Dimension(0,40));a.setLineWrap(true);a.setWrapStyleWord(true);a.putClientProperty("JComponent.roundRect",true);a.setBorder(new EmptyBorder(8,8,8,8));return a;}
    private static JScrollPane scroll(Component c){RoundedScrollPane s=new RoundedScrollPane(c);s.setBorder(new RoundedBorder(new Color(218,221,227),12));s.putClientProperty("JComponent.roundRect",true);s.getViewport().setOpaque(false);if(c instanceof JTextArea area)area.setOpaque(false);s.getVerticalScrollBar().setOpaque(false);s.getHorizontalScrollBar().setOpaque(false);s.getVerticalScrollBar().putClientProperty("JComponent.roundRect",true);s.getHorizontalScrollBar().putClientProperty("JComponent.roundRect",true);s.getVerticalScrollBar().setUnitIncrement(36);s.getVerticalScrollBar().setBlockIncrement(180);s.getHorizontalScrollBar().setUnitIncrement(36);return s;}
    private static JComponent roundedTextArea(JTextArea area){JPanel p=new JPanel(new BorderLayout()){protected void paintComponent(Graphics g){Graphics2D g2=(Graphics2D)g.create();g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING,RenderingHints.VALUE_ANTIALIAS_ON);g2.setColor(UIManager.getColor("TextArea.background"));g2.fillRoundRect(0,0,getWidth(),getHeight(),14,14);g2.dispose();}};p.setOpaque(false);p.setBorder(new RoundedBorder(new Color(218,221,227),14));area.setOpaque(false);p.add(area);return p;}
    private static Border titled(String t){TitledBorder title=new TitledBorder(new RoundedBorder(new Color(220,223,228),14),t,TitledBorder.CENTER,TitledBorder.TOP);return new CompoundBorder(title,new EmptyBorder(6,8,8,8));}
    private static int row(JPanel p,GridBagConstraints c,int r,String n,JComponent v){c.gridwidth=1;c.gridx=0;c.gridy=r;c.weightx=0;p.add(new JLabel(n),c);c.gridx=1;c.weightx=1;p.add(v,c);return r+1;}
    private static JComponent labeled(String n,JComponent v){JPanel p=new JPanel(new BorderLayout(5,0));p.setOpaque(false);p.add(new JLabel(n),BorderLayout.WEST);p.add(v);return p;}
    private static void applyLook(){if(dark)FlatDarkLaf.setup();else FlatLightLaf.setup();Color bg=dark?new Color(32,32,32):new Color(243,243,243);Color field=dark?new Color(46,46,46):new Color(252,252,252);Color selected=dark?new Color(53,67,88):new Color(222,232,249);UIManager.put("Panel.background",bg);UIManager.put("Viewport.background",bg);UIManager.put("RootPane.background",bg);UIManager.put("RootPane.border",new EmptyBorder(0,0,0,0));UIManager.put("TitlePane.background",bg);UIManager.put("TitlePane.inactiveBackground",bg);UIManager.put("TitlePane.unifiedBackground",true);UIManager.put("TextField.background",field);UIManager.put("TextArea.background",field);UIManager.put("Table.background",bg);UIManager.put("Table.foreground",dark?new Color(235,235,235):new Color(32,32,32));UIManager.put("Table.selectionForeground",dark?new Color(245,245,245):new Color(24,24,24));UIManager.put("Table.selectionBackground",selected);UIManager.put("TableHeader.background",field);UIManager.put("ScrollPane.background",bg);UIManager.put("ScrollBar.track",bg);UIManager.put("ScrollBar.hoverTrackColor",bg);UIManager.put("ScrollBar.thumb",dark?new Color(82,82,82):new Color(180,180,180));UIManager.put("ScrollBar.hoverThumbColor",dark?new Color(110,110,110):new Color(145,145,145));UIManager.put("ScrollBar.trackArc",999);UIManager.put("ScrollBar.thumbArc",999);UIManager.put("ScrollBar.showButtons",false);UIManager.put("PopupMenu.background",field);UIManager.put("PopupMenu.borderCornerRadius",14);UIManager.put("PopupMenu.dropShadowPainted",true);UIManager.put("MenuItem.selectionArc",12);UIManager.put("MenuItem.margin",new Insets(6,10,6,10));UIManager.put("ComboBox.buttonStyle","button");Font font=findFont();UIManager.put("defaultFont",font);UIManager.put("Button.arc",14);UIManager.put("Component.arc",14);UIManager.put("TextComponent.arc",14);UIManager.put("ScrollPane.arc",14);UIManager.put("ScrollBar.width",8);UIManager.put("Table.rowHeight",40);UIManager.put("Component.focusWidth",1);UIManager.put("Button.innerFocusWidth",0);}
    private static Font findFont(){for(String name:GraphicsEnvironment.getLocalGraphicsEnvironment().getAvailableFontFamilyNames())if(name.equalsIgnoreCase("MiSans")||name.startsWith("MiSans "))return new Font(name,Font.PLAIN,13);return new Font("Microsoft YaHei UI",Font.PLAIN,13);}
    private static boolean detectDarkMode(){try{Process p=new ProcessBuilder("reg","query","HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\Themes\\Personalize","/v","AppsUseLightTheme").redirectErrorStream(true).start();String out=new String(p.getInputStream().readAllBytes());return out.contains("0x0");}catch(Exception ignored){return false;}}

    private static final class HeaderRenderer extends DefaultTableCellRenderer { HeaderRenderer(){setOpaque(true);setHorizontalAlignment(CENTER);setBorder(new EmptyBorder(0,8,0,8));} @Override public Component getTableCellRendererComponent(JTable t,Object v,boolean s,boolean f,int r,int c){super.getTableCellRendererComponent(t,v,s,f,r,c);setHorizontalAlignment(CENTER);setFont(t.getFont().deriveFont(Font.BOLD));setBackground(UIManager.getColor("TableHeader.background"));setForeground(UIManager.getColor("TableHeader.foreground"));return this;}}
    private static final class CenterCellRenderer extends DefaultTableCellRenderer{CenterCellRenderer(){setHorizontalAlignment(CENTER);setOpaque(false);setBorder(null);}public Component getTableCellRendererComponent(JTable t,Object v,boolean s,boolean f,int r,int c){super.getTableCellRendererComponent(t,v,s,false,r,c);setHorizontalAlignment(CENTER);setForeground(UIManager.getColor("Table.foreground"));setOpaque(false);setBorder(null);return this;}}
    private static final class CheckCellRenderer extends JComponent implements javax.swing.table.TableCellRenderer{private boolean checked;public Component getTableCellRendererComponent(JTable t,Object v,boolean s,boolean f,int r,int c){checked=Boolean.TRUE.equals(v);return this;}protected void paintComponent(Graphics g){Graphics2D g2=(Graphics2D)g.create();g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING,RenderingHints.VALUE_ANTIALIAS_ON);int x=(getWidth()-16)/2,y=(getHeight()-16)/2;g2.setColor(checked?ACCENT:UIManager.getColor("Component.borderColor"));if(checked)g2.fillRoundRect(x,y,16,16,6,6);else g2.drawRoundRect(x,y,15,15,6,6);if(checked){g2.setColor(Color.WHITE);g2.setStroke(new BasicStroke(2f,BasicStroke.CAP_ROUND,BasicStroke.JOIN_ROUND));g2.drawLine(x+4,y+8,x+7,y+11);g2.drawLine(x+7,y+11,x+12,y+5);}g2.dispose();}}
    private static final class RoundedTable extends JTable{RoundedTable(AbstractTableModel model){super(model);setOpaque(false);ToolTipManager.sharedInstance().registerComponent(this);}public String getToolTipText(java.awt.event.MouseEvent e){int row=rowAtPoint(e.getPoint()),col=columnAtPoint(e.getPoint());if(row<0||col<=0)return null;Object value=getValueAt(row,col);return value==null||value.toString().isBlank()?null:value.toString();}protected void paintComponent(Graphics g){Graphics2D g2=(Graphics2D)g.create();g2.setColor(UIManager.getColor("Table.background"));g2.fillRect(0,0,getWidth(),getHeight());int row=getSelectedRow();if(row>=0){Rectangle r=getCellRect(row,0,true);r.width=getWidth();g2.setColor(UIManager.getColor("Table.selectionBackground"));g2.fillRoundRect(r.x+3,r.y+2,r.width-6,r.height-4,14,14);}g2.dispose();super.paintComponent(g);}}
    private static final class RoundedScrollPane extends JScrollPane{RoundedScrollPane(Component view){super(view);setOpaque(false);}public void paint(Graphics g){Graphics2D g2=(Graphics2D)g.create();g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING,RenderingHints.VALUE_ANTIALIAS_ON);g2.clip(new java.awt.geom.RoundRectangle2D.Float(0,0,getWidth(),getHeight(),14,14));g2.setColor(viewport.getView() instanceof JTextArea?UIManager.getColor("TextArea.background"):UIManager.getColor("Panel.background"));g2.fillRect(0,0,getWidth(),getHeight());super.paint(g2);g2.dispose();}}
    private static JComponent songHeader(){return new JPanel(new GridBagLayout()){ {setOpaque(false);String[] names={"","标题","艺术家","专辑"};for(int i=0;i<4;i++){GridBagConstraints c=new GridBagConstraints();c.gridy=0;c.gridx=i;c.fill=GridBagConstraints.BOTH;c.weighty=1;c.weightx=i==0?0:1;JLabel label=new JLabel(names[i],SwingConstants.CENTER);add(label,c);if(i==0)label.setPreferredSize(new Dimension(30,38));}} protected void paintComponent(Graphics g){Graphics2D g2=(Graphics2D)g.create();g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING,RenderingHints.VALUE_ANTIALIAS_ON);g2.setColor(UIManager.getColor("TableHeader.background"));g2.fillRoundRect(0,0,getWidth(),getHeight(),14,14);g2.dispose();super.paintComponent(g);} public Dimension getPreferredSize(){return new Dimension(0,38);}};}
    private static final class CoverView extends JComponent{private Image image;CoverView(){setOpaque(false);}void setCover(byte[] bytes){image=bytes==null?null:new ImageIcon(bytes).getImage();repaint();}protected void paintComponent(Graphics g){Graphics2D g2=(Graphics2D)g.create();g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING,RenderingHints.VALUE_ANTIALIAS_ON);java.awt.Shape shape=new java.awt.geom.RoundRectangle2D.Float(1,1,getWidth()-2,getHeight()-2,16,16);g2.clip(shape);if(image==null){g2.setColor(UIManager.getColor("TextField.background"));g2.fill(shape);g2.setClip(null);g2.setColor(UIManager.getColor("Label.disabledForeground"));String text="无封面";FontMetrics fm=g2.getFontMetrics();g2.drawString(text,(getWidth()-fm.stringWidth(text))/2,(getHeight()+fm.getAscent())/2);}else{g2.drawImage(image,1,1,getWidth()-2,getHeight()-2,null);}g2.setClip(null);g2.setColor(dark?new Color(72,72,72):new Color(205,208,214));g2.drawRoundRect(1,1,getWidth()-3,getHeight()-3,16,16);g2.dispose();}}
    private static final class RatioLayout implements LayoutManager{private final int gap;RatioLayout(int gap){this.gap=gap;}public void addLayoutComponent(String n,Component c){}public void removeLayoutComponent(Component c){}public Dimension preferredLayoutSize(Container p){return new Dimension(1000,600);}public Dimension minimumLayoutSize(Container p){return new Dimension(0,0);}public void layoutContainer(Container p){if(p.getComponentCount()<3)return;Insets i=p.getInsets();int width=p.getWidth()-i.left-i.right-gap*2,height=p.getHeight()-i.top-i.bottom;int first=(int)(width*.30),second=(int)(width*.30),third=width-first-second;p.getComponent(0).setBounds(i.left,i.top,first,height);p.getComponent(1).setBounds(i.left+first+gap,i.top,second,height);p.getComponent(2).setBounds(i.left+first+gap+second+gap,i.top,third,height);}}
    private static final class ViewportWidthPanel extends JPanel implements Scrollable{ViewportWidthPanel(LayoutManager layout){super(layout);}public Dimension getPreferredScrollableViewportSize(){return getPreferredSize();}public int getScrollableUnitIncrement(Rectangle r,int o,int d){return 36;}public int getScrollableBlockIncrement(Rectangle r,int o,int d){return 180;}public boolean getScrollableTracksViewportWidth(){return true;}public boolean getScrollableTracksViewportHeight(){return false;}}
    private static final class CenterListRenderer extends DefaultListCellRenderer {@Override public Component getListCellRendererComponent(JList<?> list,Object value,int index,boolean selected,boolean focus){JLabel label=(JLabel)super.getListCellRendererComponent(list,value,index,selected,focus);label.setHorizontalAlignment(CENTER);return label;}}

    private static final class RoundedBorder extends AbstractBorder {private final Color color;private final int arc;RoundedBorder(Color c,int a){color=c;arc=a;}public void paintBorder(Component c,Graphics g,int x,int y,int w,int h){Graphics2D g2=(Graphics2D)g.create();g2.setColor(dark?new Color(72,72,72):color);g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING,RenderingHints.VALUE_ANTIALIAS_ON);g2.drawRoundRect(x,y,w-1,h-1,arc,arc);g2.dispose();}public Insets getBorderInsets(Component c){return new Insets(5,7,5,7);}}
    private static final class SongModel extends AbstractTableModel {final List<AudioTagData> items=new ArrayList<>();final List<Boolean> checked=new ArrayList<>();void add(AudioTagData d){int r=items.size();items.add(d);checked.add(true);fireTableRowsInserted(r,r);}void clear(){int size=items.size();items.clear();checked.clear();if(size>0)fireTableRowsDeleted(0,size-1);}void selectAll(boolean v){for(int i=0;i<checked.size();i++)checked.set(i,v);fireTableDataChanged();}List<Integer> checkedRows(){List<Integer> r=new ArrayList<>();for(int i=0;i<checked.size();i++)if(checked.get(i))r.add(i);return r;}public int getRowCount(){return items.size();}public int getColumnCount(){return 4;}public String getColumnName(int c){return new String[]{"","标题","艺术家","专辑"}[c];}public Class<?> getColumnClass(int c){return c==0?Boolean.class:String.class;}public boolean isCellEditable(int r,int c){return false;}public Object getValueAt(int r,int c){AudioTagData d=items.get(r);return switch(c){case 0->checked.get(r);case 1->d.displayName();case 2->d.artist();default->d.album();};}public void setValueAt(Object v,int r,int c){if(c==0){checked.set(r,(Boolean)v);fireTableCellUpdated(r,c);}}}
}
